#-  Travis CI configuration file

#-  .travis.yml ~~
#                                                       ~~ (c) SRW, 15 Jul 2013
#                                                   ~~ last updated 21 Mar 2014

before_install:
    -   sudo apt-get update -qq
    -   sudo apt-get install -qq curl git imagemagick make

language: node_js

node_js:
    -   "0.10"

script: "make web-service"

#-  vim:set syntax=yaml:
