#-  Travis CI configuration file

#-  .travis.yml ~~
#                                                       ~~ (c) SRW, 15 Jul 2013
#                                                   ~~ last updated 18 Aug 2014

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq imagemagick

before_script:
  - psql -c "create database ${USER};" -U postgres
  - make $app db=$db
  - sleep 5

env:
  - app=node-app db=couch
  - app=node-app db=mongo
  - app=node-app db=postgres
  - app=node-app db=redis
  - app=node-app db=sqlite

language: node_js

matrix:
  include:
    - node_js: "0.10"
      env: app=ruby-app db=mongo

node_js:
  - "0.10"
  - "0.8"

script:
  - make check

services:
  - couchdb
  - mongodb
  - redis-server

#-  vim:set syntax=yaml:
