#-  Travis CI configuration file

#-  .travis.yml ~~
#
#   These instructions test the Node.js version of QMachine ten times -- two
#   different versions of Node.js against 5 databases each. I haven't figured
#   out how to test the Ruby version yet.
#
#                                                       ~~ (c) SRW, 15 Jul 2013
#                                                   ~~ last updated 18 Aug 2014

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq imagemagick

before_script:
  - psql -c "create database ${USER};" -U postgres
  - make node-app db=$db
  - sleep 5

env:
  - db=couch
  - db=mongo
  - db=postgres
  - db=redis
  - db=sqlite

language: node_js

node_js:
  - "0.10"
  - "0.8"

script:
  - make check

services:
  - couchdb
  - mongodb
  - redis-server

#-  vim:set syntax=yaml:
