#-  Travis CI configuration file

#-  .travis.yml ~~
#
#   These instructions run QMachine's tests 19 times -- 2 versions of Node.js
#   and the latest io.js against 5 databases each, plus the latest stable MRI
#   Ruby against 4 databases. CouchDB support is probably going to be removed
#   soon, so its failures are allowed (and, at this point, somewhat expected).
#   The io.js runs are allowed to fail because I haven't had time to explore
#   all its differences yet. The databases other than Mongo are allowed to fail
#   for the Ruby version because that support is still experimental.
#
#                                                       ~~ (c) SRW, 15 Jul 2013
#                                                   ~~ last updated 05 Apr 2015

#addons:
#  postgres: '9.2'          # see http://goo.gl/w344UT and http://goo.gl/3ef8hF

before_install:
  - npm install -g npm@latest
  - rvm use 'ruby-2.2.1' --install --binary --fuzzy

before_script:
  - psql -c "create database ${USER};" -U postgres
  - make $backend db=$db
  - sleep 5

env:
  global:
    - backend=node-app
  matrix:
    - db=couch
    - db=mongo
    - db=postgres
    - db=redis
    - db=sqlite

language: node_js

matrix:
  allow_failures:
    - env: db=couch
    - env: backend=ruby-app db=postgres
    - env: backend=ruby-app db=redis
    - env: backend=ruby-app db=sqlite
    - node_js: '0.8'
    - node_js: iojs
  include:
    - node_js: '0.12'
      env: backend=ruby-app db=mongo
    - node_js: '0.12'
      env: backend=ruby-app db=postgres
    - node_js: '0.12'
      env: backend=ruby-app db=redis
    - node_js: '0.12'
      env: backend=ruby-app db=sqlite

node_js:
  - '0.12'
  - '0.10'
  - iojs

script:
  - make check

services:
  - couchdb
  - mongodb
  - redis-server

sudo: false

#-  vim:set syntax=yaml:
