#-  Travis CI configuration file

#-  .travis.yml ~~
#
#   These instructions run QMachine's tests 12 times -- 2 versions of Node.js
#   against 5 databases each, plus Ruby against 2 databases. CouchDB support is
#   probably going to be removed soon, so its failures are allowed (and, at
#   this point, somewhat expected ...).
#
#                                                       ~~ (c) SRW, 15 Jul 2013
#                                                   ~~ last updated 30 Jan 2015

before_install:
  - npm install -g npm@latest
  - rvm use 'ruby-2.2.0' --install --binary --fuzzy

before_script:
  - psql -c "create database ${USER};" -U postgres
  - make $backend db=$db
  - sleep 5

env:
  global:
    - backend=node-app
  matrix:
    - db=couch
    - db=mongo
    - db=postgres
    - db=redis
    - db=sqlite

language: node_js

matrix:
  allow_failures:
    - env: db=couch
  include:
    - node_js: '0.10'
      env: backend=ruby-app db=mongo
    - node_js: '0.10'
      env: backend-ruby-app db=sqlite

node_js:
  - '0.10'
  - '0.8'

script:
  - make check

services:
  - couchdb
  - mongodb
  - redis-server

sudo: false

#-  vim:set syntax=yaml:
