#-  Travis CI configuration file

#-  .travis.yml ~~
#                                                       ~~ (c) SRW, 15 Jul 2013
#                                                   ~~ last updated 08 Aug 2014

before_install:
    -   sudo apt-get update -qq
    -   sudo apt-get install -qq git imagemagick make

language: node_js

node_js:
    -   "0.10"
    -   "0.8"

script: "make check-versions homepage npm-module testpage"

#-  vim:set syntax=yaml:
