#-  Travis CI configuration file

#-  .travis.yml ~~
#                                                       ~~ (c) SRW, 15 Jul 2013
#                                                   ~~ last updated 15 Jul 2013

before_install:
    -   sudo apt-get update -qq
    -   sudo apt-get install -qq curl imagemagick libsqlite3-dev

node_js:
    -   "0.10"

script: "make browser-client"

#-  vim:set syntax=yaml:
