#-  Travis CI configuration file

#-  .travis.yml ~~
#
#   These instructions run QMachine's tests eleven times -- two versions of
#   Node.js against 5 databases each, plus Ruby against Mongo.
#
#                                                       ~~ (c) SRW, 15 Jul 2013
#                                                   ~~ last updated 18 Aug 2014

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq imagemagick
  - rvm use '2.1.2' --install --binary --fuzzy
  - ruby --version

before_script:
  - psql -c "create database ${USER};" -U postgres
  - make $backend db=$db
  - sleep 5

env:
    - backend=node-app db=couch
    - backend=node-app db=mongo
    - backend=node-app db=postgres
    - backend=node-app db=redis
    - backend=node-app db=sqlite

language: node_js

matrix:
  include:
    - node_js: "0.10"
      env: backend=ruby-app db=mongo

node_js:
  - "0.10"
  - "0.8"

script:
  - make check

services:
  - couchdb
  - mongodb
  - redis-server

#-  vim:set syntax=yaml:
